---
- name: Install Podman and Cockpit
  ansible.builtin.apt:
    name:
      - podman
      - cockpit
      - cockpit-podman
    update_cache: true

- name: Enable and start Cockpit
  ansible.builtin.systemd:
    name: cockpit
    enabled: true
    state: started
