- name: Install Podman and Cockpit
  apt:
    name:
      - podman
      - cockpit
      - cockpit-podman
    update_cache: true

- name: Enable and start Cockpit
  systemd:
    name: cockpit
    enabled: yes
    state: started
