---
- name: Create adguardhome directory
  ansible.builtin.file:
    path: "/opt/adguardhome"
    state: directory
    owner: pi
    group: pi
    mode: '0755'

- name: Copy whitelist file
  ansible.builtin.copy:
    src: adguardhome/whitelist.txt
    dest: /opt/adguardhome/whitelist.txt
    owner: pi
    group: pi
    mode: '0644'

- name: Copy podman-compose.yaml
  ansible.builtin.copy:
    src: adguardhome/podman-compose.yaml
    dest: /opt/adguardhome/podman-compose.yaml
    owner: pi
    group: pi
    mode: '0644'

- name: Template AdGuard config file
  ansible.builtin.template:
    src: adguardhome/conf/AdGuardHome.yaml.j2
    dest: /opt/adguardhome/AdGuardHome.yaml
    owner: pi
    group: pi
    mode: '0644'

- name: Start AdGuard Home with podman-compose
  become: false
  ansible.builtin.shell: |
    cd /opt/adguardhome
    podman-compose up -d
  args:
    executable: /bin/bash
  changed_when: false

- name: Copy unbound podman-compose.yaml
  ansible.builtin.copy:
    src: unbound/podman-compose.yaml
    dest: /opt/unbound/podman-compose.yaml
    owner: pi
    group: pi
    mode: '0644'

- name: Start Unbound with podman-compose
  become: false
  ansible.builtin.shell: |
    cd /opt/unbound
    podman-compose up -d
  args:
    executable: /bin/bash
  changed_when: false

- name: Create scrypted directory
  ansible.builtin.file:
    path: "/opt/scrypted"
    state: directory
    owner: pi
    group: pi
    mode: '0755'

- name: Copy scrypted podman-compose.yaml
  ansible.builtin.copy:
    src: scrypted/podman-compose.yaml
    dest: /opt/scrypted/podman-compose.yaml
    owner: pi
    group: pi
    mode: '0644'

- name: Start Scrypted with podman-compose
  become: false
  ansible.builtin.shell: |
    cd /opt/scrypted
    podman-compose up -d
  args:
    executable: /bin/bash
  changed_when: false
